#!/bin/bash
# ============================================================================
# 武士団マルチエージェントシステム v10.1 - 月次メンテナンス (反省会)
# ============================================================================
#
# 【コア要件】必ず達成すべきこと:
#   1. メンテナンス実行スクリプトの作成
#   2. cron ジョブの設定 (毎月1日 9:00)
#
# 【最終結果】このスクリプト完了後の状態:
#   - setup/run_maintenance.sh が実行可能
#   - cron に月次ジョブが登録済み
#   - logs/ と reports/maintenance/ ディレクトリが作成済み
#
# 【動作保証】
#   - crontab コマンドがあれば異常終了しない
#   - Python 環境がなくても cron 設定は可能
#
# Usage:
#   bash maintenance.sh install    # cron 設定
#   bash maintenance.sh uninstall  # cron 削除
#   bash maintenance.sh run        # 今すぐ実行
#   bash maintenance.sh status     # 状態確認
#
# ============================================================================

# エラー時に即座に終了しない
# set -e は使わない

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
VENV_DIR="${PROJECT_DIR}/.venv"
MAINTENANCE_SCRIPT="${PROJECT_DIR}/setup/run_maintenance.sh"
LOG_DIR="${PROJECT_DIR}/logs"
CRON_JOB="0 9 1 * * ${MAINTENANCE_SCRIPT} >> ${LOG_DIR}/maintenance.log 2>&1"

# ============================================================================
# 結果トラッキング
# ============================================================================

declare -A RESULTS
CORE_FAILED=0

mark_success() {
    RESULTS["$1"]="OK"
}

mark_failed() {
    RESULTS["$1"]="FAILED"
    if [[ "$2" == "core" ]]; then
        CORE_FAILED=1
    fi
}

mark_skipped() {
    RESULTS["$1"]="SKIPPED"
}

# ============================================================================
# ユーティリティ関数
# ============================================================================

log_info() {
    echo "[INFO] $1"
}

log_success() {
    echo "[OK] $1"
}

log_warning() {
    echo "[WARN] $1"
}

log_error() {
    echo "[ERROR] $1"
}

# ============================================================================
# メンテナンス実行スクリプト作成
# ============================================================================

create_runner() {
    log_info "メンテナンス実行スクリプトを作成中..."

    mkdir -p "${LOG_DIR}"
    mkdir -p "${PROJECT_DIR}/reports/maintenance"

    cat > "$MAINTENANCE_SCRIPT" << RUNNER
#!/bin/bash
# ============================================================================
# 武士団 v10.1 - 月次メンテナンス実行スクリプト
# Auto-generated by maintenance.sh
# ============================================================================

PROJECT_DIR="${PROJECT_DIR}"
VENV_DIR="${VENV_DIR}"

echo "============================================="
echo "  武士団 月次メンテナンス (反省会)"
echo "  実行日時: \$(date '+%Y-%m-%d %H:%M:%S')"
echo "============================================="

# 仮想環境確認
if [ -f "\${VENV_DIR}/bin/activate" ]; then
    source "\${VENV_DIR}/bin/activate"
else
    echo "[ERROR] venv not found at \${VENV_DIR}"
    echo "  setup/install.sh --user を実行してください"
    exit 1
fi

cd "\$PROJECT_DIR"

# メンテナンス実行
if python -m bushidan.cli maintenance run 2>/dev/null; then
    echo "[OK] メンテナンス完了"
else
    echo "[WARN] メンテナンス実行に問題がありました"
fi

echo ""
echo "============================================="
echo "  完了: \$(date '+%Y-%m-%d %H:%M:%S')"
echo "============================================="
RUNNER

    if chmod +x "$MAINTENANCE_SCRIPT"; then
        mark_success "runner_script"
        log_success "実行スクリプト作成: ${MAINTENANCE_SCRIPT}"
    else
        mark_failed "runner_script" "core"
        log_error "実行スクリプト作成失敗"
    fi
}

# ============================================================================
# cron 操作
# ============================================================================

install_cron() {
    log_info "cron ジョブをインストール中..."

    create_runner

    # crontab コマンド確認
    if ! command -v crontab &>/dev/null; then
        log_warning "crontab コマンドがありません"
        log_info "手動で以下を cron に追加してください:"
        echo "  $CRON_JOB"
        mark_skipped "cron_install"
        return 0
    fi

    # 既存チェック
    if crontab -l 2>/dev/null | grep -q "run_maintenance.sh"; then
        log_success "cron 既に設定済み"
        mark_success "cron_install"
        return 0
    fi

    # cron 追加
    if (crontab -l 2>/dev/null; echo "$CRON_JOB") | crontab -; then
        mark_success "cron_install"
        log_success "cron 設定完了: 毎月1日 9:00"
    else
        mark_failed "cron_install"
        log_error "cron 設定失敗"
    fi
}

uninstall_cron() {
    log_info "cron ジョブを削除中..."

    if ! command -v crontab &>/dev/null; then
        log_warning "crontab コマンドがありません"
        mark_skipped "cron_uninstall"
        return 0
    fi

    if crontab -l 2>/dev/null | grep -q "run_maintenance.sh"; then
        if crontab -l | grep -v "run_maintenance.sh" | crontab -; then
            mark_success "cron_uninstall"
            log_success "cron 削除完了"
        else
            mark_failed "cron_uninstall"
            log_error "cron 削除失敗"
        fi
    else
        log_info "cron 設定なし (削除不要)"
        mark_success "cron_uninstall"
    fi
}

# ============================================================================
# 状態確認
# ============================================================================

show_status() {
    echo ""
    echo "============================================="
    echo "  月次メンテナンス設定状況"
    echo "============================================="
    echo ""

    # 実行スクリプト
    if [ -f "$MAINTENANCE_SCRIPT" ]; then
        echo "  [OK] 実行スクリプト: ${MAINTENANCE_SCRIPT}"
        mark_success "status_script"
    else
        echo "  [--] 実行スクリプト: 未作成"
        mark_skipped "status_script"
    fi

    # cron
    if command -v crontab &>/dev/null; then
        if crontab -l 2>/dev/null | grep -q "run_maintenance.sh"; then
            echo "  [OK] cron: 設定済み (毎月1日 9:00)"
            mark_success "status_cron"
        else
            echo "  [--] cron: 未設定"
            mark_skipped "status_cron"
        fi
    else
        echo "  [--] cron: crontab コマンドなし"
        mark_skipped "status_cron"
    fi

    # ログディレクトリ
    if [ -d "$LOG_DIR" ]; then
        echo "  [OK] ログディレクトリ: ${LOG_DIR}"
        mark_success "status_log_dir"
    else
        echo "  [--] ログディレクトリ: 未作成"
        mark_skipped "status_log_dir"
    fi

    # レポートディレクトリ
    REPORTS_DIR="${PROJECT_DIR}/reports/maintenance"
    if [ -d "$REPORTS_DIR" ]; then
        REPORT_COUNT=$(ls -1 "$REPORTS_DIR"/*.json 2>/dev/null | wc -l || echo "0")
        echo "  [OK] レポート: ${REPORT_COUNT}件 (${REPORTS_DIR})"
        mark_success "status_reports"
    else
        echo "  [--] レポートディレクトリ: 未作成"
        mark_skipped "status_reports"
    fi

    # 次回メンテナンス日
    echo ""
    if [ -f "${VENV_DIR}/bin/activate" ]; then
        source "${VENV_DIR}/bin/activate" 2>/dev/null
        cd "$PROJECT_DIR"
        python -c "
from datetime import datetime, timedelta
import calendar
now = datetime.now()
# 今月1日 or 来月1日
if now.day == 1:
    next_date = now.replace(hour=9, minute=0, second=0)
else:
    if now.month == 12:
        next_date = now.replace(year=now.year+1, month=1, day=1, hour=9, minute=0, second=0)
    else:
        next_date = now.replace(month=now.month+1, day=1, hour=9, minute=0, second=0)
print(f'  次回メンテナンス: {next_date.strftime(\"%Y-%m-%d %H:%M\")}')
" 2>/dev/null || echo "  次回メンテナンス: 計算不可"
    else
        echo "  次回メンテナンス: Python環境未設定"
    fi

    echo ""
    echo "============================================="
}

# ============================================================================
# 今すぐ実行
# ============================================================================

run_now() {
    log_info "メンテナンスを実行中..."

    if [ ! -f "$MAINTENANCE_SCRIPT" ]; then
        create_runner
    fi

    if [ -x "$MAINTENANCE_SCRIPT" ]; then
        bash "$MAINTENANCE_SCRIPT"
        mark_success "run_now"
    else
        log_error "実行スクリプトが見つかりません"
        mark_failed "run_now"
    fi
}

# ============================================================================
# 最終レポート
# ============================================================================

print_final_report() {
    local action="$1"

    echo ""
    echo "============================================="
    echo "  メンテナンス設定 - 完了レポート ($action)"
    echo "============================================="
    echo ""

    echo "【処理結果】"
    for key in "${!RESULTS[@]}"; do
        local status="${RESULTS[$key]}"
        case "$status" in
            OK)      echo "  [OK]      $key" ;;
            FAILED)  echo "  [FAILED]  $key" ;;
            SKIPPED) echo "  [SKIP]    $key" ;;
        esac
    done

    echo ""

    if [ $CORE_FAILED -eq 1 ]; then
        echo "【状態】エラーがあります"
    else
        echo "【状態】正常完了"
    fi

    echo ""
    echo "============================================="
}

# ============================================================================
# ヘルプ
# ============================================================================

show_usage() {
    echo "Usage: $0 [install|uninstall|run|status]"
    echo ""
    echo "Commands:"
    echo "  install    cron 設定 (毎月1日 9:00)"
    echo "  uninstall  cron 削除"
    echo "  run        今すぐ実行"
    echo "  status     設定状況確認"
    echo ""
    echo "【コア要件】"
    echo "  1. メンテナンス実行スクリプト作成"
    echo "  2. cron ジョブ設定"
    echo ""
    echo "【最終結果】"
    echo "  - 毎月1日 9:00 に自動メンテナンス実行"
}

# ============================================================================
# エントリーポイント
# ============================================================================

case "${1:-status}" in
    install)
        echo ""
        echo "============================================="
        echo "  月次メンテナンス cron インストール"
        echo "============================================="
        install_cron
        print_final_report "install"
        show_status
        ;;
    uninstall)
        echo ""
        echo "============================================="
        echo "  月次メンテナンス cron アンインストール"
        echo "============================================="
        uninstall_cron
        print_final_report "uninstall"
        ;;
    run)
        run_now
        ;;
    status)
        show_status
        ;;
    --help|-h)
        show_usage
        ;;
    *)
        log_error "不明なコマンド: $1"
        show_usage
        exit 1
        ;;
esac

exit $CORE_FAILED
